version: "3.7"
services:
  postgres:
    container_name: pg_container
    image: postgis/postgis:13-master
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOSTNAME: localhost
      TZ: "Asia/Seoul"
    ports:
      - "5432:5432"